-- ============================================================================
-- FabricsBossArena — Admin Dashboard setup
-- Run this ONCE in the Supabase SQL editor (Dashboard > SQL Editor > New query).
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / OR REPLACE).
-- ============================================================================

-- 1) Admin flag on profiles ---------------------------------------------------
alter table public.profiles
  add column if not exists is_admin boolean not null default false;

-- 2) Categories table ---------------------------------------------------------
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now()
);

-- Seed categories from any category values already used by existing products,
-- so the admin dropdown isn't empty on first load.
insert into public.categories (name)
select distinct trim(category)
from public.products
where category is not null and trim(category) <> ''
on conflict (name) do nothing;

-- 3) New product columns (existing columns/data are untouched) ---------------
alter table public.products
  add column if not exists description text,
  add column if not exists img_url text,
  add column if not exists stock integer not null default 0,
  add column if not exists featured boolean not null default false,
  add column if not exists is_available boolean not null default true,
  add column if not exists created_at timestamptz not null default now();

-- Note: the app's mapProduct.ts already reads description/desc and img_url/img
-- interchangeably, so this is compatible whichever naming your existing rows use.

-- 4) Helper function to check admin status (security definer avoids recursive
--    RLS lookups when policies on `profiles` itself reference `profiles`). ---
create or replace function public.is_admin_user()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(
    (select is_admin from public.profiles where id = auth.uid()),
    false
  );
$$;

-- 5) Row Level Security -------------------------------------------------------
alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.profiles enable row level security;

-- Products: anyone can read; only admins can write.
drop policy if exists "Public read products" on public.products;
create policy "Public read products" on public.products
  for select using (true);

drop policy if exists "Admins manage products" on public.products;
create policy "Admins manage products" on public.products
  for all using (public.is_admin_user()) with check (public.is_admin_user());

-- Categories: anyone can read; only admins can write.
drop policy if exists "Public read categories" on public.categories;
create policy "Public read categories" on public.categories
  for select using (true);

drop policy if exists "Admins manage categories" on public.categories;
create policy "Admins manage categories" on public.categories
  for all using (public.is_admin_user()) with check (public.is_admin_user());

-- Profiles: users manage their own row; admins can read all (to check is_admin).
drop policy if exists "Users read own or admin reads all profiles" on public.profiles;
create policy "Users read own or admin reads all profiles" on public.profiles
  for select using (auth.uid() = id or public.is_admin_user());

drop policy if exists "Users insert own profile" on public.profiles;
create policy "Users insert own profile" on public.profiles
  for insert with check (auth.uid() = id);

drop policy if exists "Users update own profile" on public.profiles;
create policy "Users update own profile" on public.profiles
  for update using (auth.uid() = id) with check (auth.uid() = id);

-- 6) Storage bucket for product images ---------------------------------------
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do nothing;

drop policy if exists "Public read product images" on storage.objects;
create policy "Public read product images" on storage.objects
  for select using (bucket_id = 'product-images');

drop policy if exists "Admins upload product images" on storage.objects;
create policy "Admins upload product images" on storage.objects
  for insert with check (
    bucket_id = 'product-images' and public.is_admin_user()
  );

drop policy if exists "Admins update product images" on storage.objects;
create policy "Admins update product images" on storage.objects
  for update using (
    bucket_id = 'product-images' and public.is_admin_user()
  ) with check (
    bucket_id = 'product-images' and public.is_admin_user()
  );

drop policy if exists "Admins delete product images" on storage.objects;
create policy "Admins delete product images" on storage.objects
  for delete using (
    bucket_id = 'product-images' and public.is_admin_user()
  );

-- ============================================================================
-- 7) FINAL STEP (do this manually, once you have an account):
--    Promote your account to admin by email:
--
--    update public.profiles set is_admin = true where email = 'you@example.com';
--
--    You must already have signed up on the site (or via /admin/login flow —
--    sign up on the storefront first, then run the line above).
-- ============================================================================
