-- ============================================================================
-- FabricsBossArena — Newsletter subscribers
-- Run this ONCE in the Supabase SQL editor (Dashboard > SQL Editor > New query).
-- Safe to re-run (IF NOT EXISTS / OR REPLACE).
--
-- Requires supabase/admin_setup.sql to have already been run (reuses the
-- public.is_admin_user() helper it creates).
-- ============================================================================

create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text unique not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_newsletter_subscribers_created_at
  on public.newsletter_subscribers (created_at desc);

alter table public.newsletter_subscribers enable row level security;

-- Anyone (including anonymous visitors) can subscribe.
drop policy if exists "Anyone can subscribe" on public.newsletter_subscribers;
create policy "Anyone can subscribe" on public.newsletter_subscribers
  for insert with check (true);

-- Only admins can view or remove the subscriber list — protects emails from
-- being readable by the public.
drop policy if exists "Admins read subscribers" on public.newsletter_subscribers;
create policy "Admins read subscribers" on public.newsletter_subscribers
  for select using (public.is_admin_user());

drop policy if exists "Admins delete subscribers" on public.newsletter_subscribers;
create policy "Admins delete subscribers" on public.newsletter_subscribers
  for delete using (public.is_admin_user());

-- ============================================================================
-- Duplicate emails are rejected at the database level by the UNIQUE
-- constraint on `email`; the client (src/components/NewsletterSignup.tsx)
-- catches that specific error (Postgres code 23505) and shows a friendly
-- "you're already subscribed" message instead of a raw DB error.
-- ============================================================================
