-- ============================================================================
-- FabricsBossArena — Order Management System setup
-- Run this ONCE in the Supabase SQL editor (Dashboard > SQL Editor > New query).
-- Safe to re-run: every statement is idempotent (IF NOT EXISTS / OR REPLACE).
--
-- Requires supabase/admin_setup.sql to have already been run (this migration
-- reuses the public.is_admin_user() helper it creates).
-- ============================================================================

-- 1) Orders table -------------------------------------------------------------
-- Created with the full target schema in case the table doesn't exist yet.
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  reference text unique not null,
  items jsonb not null default '[]'::jsonb,
  subtotal numeric(12, 2) not null default 0,
  total numeric(12, 2) not null default 0,
  status text not null default 'pending',
  payment_status text not null default 'pending',
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  customer_address text not null,
  customer_city text,
  customer_state text,
  order_notes text,
  status_history jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);

-- If the table already existed (as it did for the storefront's checkout
-- flow) these add whatever columns are still missing without touching data.
alter table public.orders
  add column if not exists subtotal numeric(12, 2) not null default 0,
  add column if not exists payment_status text not null default 'pending',
  add column if not exists customer_email text,
  add column if not exists customer_city text,
  add column if not exists customer_state text,
  add column if not exists order_notes text,
  add column if not exists status_history jsonb not null default '[]'::jsonb,
  add column if not exists updated_at timestamptz,
  add column if not exists created_at timestamptz not null default now();

-- Backfill a unique constraint on reference if the table pre-existed without one.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'orders_reference_key'
  ) then
    alter table public.orders add constraint orders_reference_key unique (reference);
  end if;
exception when duplicate_table or duplicate_object then
  null;
end $$;

-- Keep updated_at current on every row change.
create or replace function public.set_orders_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
  before update on public.orders
  for each row
  execute function public.set_orders_updated_at();

-- 2) Indexes for admin search / filter / sort ---------------------------------
create index if not exists idx_orders_status on public.orders (status);
create index if not exists idx_orders_created_at on public.orders (created_at desc);
create index if not exists idx_orders_reference on public.orders (reference);
create index if not exists idx_orders_customer_name on public.orders (customer_name);

-- 3) Row Level Security -------------------------------------------------------
alter table public.orders enable row level security;

-- Customers can create their own orders at checkout.
drop policy if exists "Customers insert own orders" on public.orders;
create policy "Customers insert own orders" on public.orders
  for insert with check (auth.uid() = user_id);

-- Customers can view their own orders (e.g. an "Account > Orders" page);
-- admins can view every order.
drop policy if exists "Customers read own orders or admin reads all" on public.orders;
create policy "Customers read own orders or admin reads all" on public.orders
  for select using (auth.uid() = user_id or public.is_admin_user());

-- Only admins can update orders (status, payment status, notes, etc).
drop policy if exists "Admins update orders" on public.orders;
create policy "Admins update orders" on public.orders
  for update using (public.is_admin_user()) with check (public.is_admin_user());

-- Only admins can delete orders.
drop policy if exists "Admins delete orders" on public.orders;
create policy "Admins delete orders" on public.orders
  for delete using (public.is_admin_user());

-- ============================================================================
-- Done. The storefront checkout (src/pages/Cart.tsx) writes new orders, and
-- the admin dashboard (/admin/orders) reads, updates, and deletes them.
-- ============================================================================
